# Default deployment values for ers-perfdata-parser
replicaCount: 1
image:
  repository: quay.cnqr.delivery/inception/ers-perfdata-parser
  tag: feature
  pullPolicy: Always
service:
  type: ClusterIP
  clusterIP: None # Headless service, only cluster members
  externalPort: 80
  internalPort: 80
  hzPort: 5701
  namespace: inception
env:
  springProfile: qa
  gitCommit: gitCommitDefault
  jvmHeapSize: 1024M
  LOG_ROOT_LEVEL: INFO
  k8sNamespace: inception
pod:
  initialDelaySeconds: 90
  timeoutSeconds: 60
  maxReplicas: 2
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi
highavailability:
  targetCPUUtilizationPercentage: 50
rbac:
  create: false
