# integration specific deployment values
replicaCount: 1
image:
  tag: develop
service:
  name: ers-perfdata-parser-integration
env:
  springProfile: integration
  jvmHeapSize: 3072M
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi
rbac:
  create: true
ingress:
  enabled: true
  hosts:
    - ers-perfdata-parser.k8s.cnqr.tech
    - ers-perfdata-parser.service.cnqr.tech
  tls:
    - hosts:
        - ers-perfdata-parser.k8s.cnqr.tech
        - ers-perfdata-parser.service.cnqr.tech