# =========================================================
# 1st action == Set of pods for Hazelcast Servers
# =========================================================
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.service.name }}
  namespace:  {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Values.service.name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}-{{ .Values.service.name }}
    heritage: {{ .Release.Service }}-{{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.service.name }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        release: {{ .Release.Name }}-{{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          {{- if index .Values.image "ers-hazelcast" }}
          # devtest (k8s workflow) image parameter
          image: {{ index .Values.image "ers-hazelcast" }}
          {{- else }}
          # non-devtest image parameter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
              name: internal-port
            - containerPort: {{ .Values.service.hzPort }}
              name: hz-port
          #livenessProbe:
           # httpGet:
             # path: /
             # port: {{ .Values.service.internalPort }}
           # initialDelaySeconds: {{default "60" .Values.pod.initialDelaySeconds}}
           # timeoutSeconds: {{default "2" .Values.pod.timeoutSeconds}}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.internalPort }}
          #  initialDelaySeconds: {{default "60" .Values.pod.initialDelaySeconds}}
          #  timeoutSeconds: {{default "2" .Values.pod.timeoutSeconds}}
          env:
            - name: SPRING_PROFILE
              value: {{default "qa" .Values.env.springProfile}}
            - name: GIT_COMMIT
              value: {{ .Values.env.gitCommit }}
            - name: JVM_HEAP_SIZE
              value: {{ .Values.env.jvmHeapSize }}
            - name: LOG_ROOT_LEVEL
              value: {{ .Values.env.LOG_ROOT_LEVEL }}
            - name: K8S_NAMESPACE
              value: {{ .Values.env.k8sNamespace }}
            - name: MANCENTER_URL
              value:  {{ .Values.env.manCenterUrl }}
            - name: DEPLOYMENT_ID
              value: ers-hazelcast-{{ .Values.env.springProfile }}-{{ now.Unix }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
