# Using Kubernetes API to discover Hazelcast members requires granting certain permissions
# Therefore, we require role and rolebinding.yaml

{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Values.service.name }}-{{ .Chart.Version | replace "+" "_" }}
    release: "{{ .Release.Name }}-{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.service.namespace }}
  {{ end }}